### ISSUE TITLE
Best way to integrate UnoCSS or TailwindCSS into Preact example?

### ISSUE THREAD

**Issue by shah** [bpevs/bext#1]
We'd like to use UnoCSS or Tailwind for our extension's UI. What's the suggested approach to incorporate UnoCSS or Tailwind into `bext` (either at the framework level or the extension level)?

**Comment by bpevs** [comment]
Hmmmm I haven't really been using these frameworks too much, so bext doesn't explicitly support this usecase at the moment, and I probably don't have the most knowledgeable answer for you. But I'd reckon there's two options here:

1 (extension-level support). Use build options that are build-agnostic (ala [TailwindCLI](https://tailwindcss.com/docs/installation) or [Play CDN](https://tailwindcss.com/docs/installation/play-cdn) or the like), and run them before the bext scripts. For instance, you could use TailwindCLI to build a css file into the "static" folder, and then link in the html ([see preact example as an example of referencing styles](https://github.com/bpevs/bext/tree/main/examples/preact_app/static)). Would be slightly awkward to run a node.js build script before a deno app, but this is likely a solution that works with bext as-is.

2 (framework-level support). It is probably possible to pass options to the [`esbuild` process of the main.js script](https://github.com/bpevs/bext/blob/main/source/main.ts#L75) via some sort of plugin or config system. This would probably be the cleanest solution in the long-term, and avoids additional build steps, but is probably take a bit of work to integrate atm (even if I add this kind of plugin system).  Mostly because not a ton of tailwind and unocss users are utilizing esbuild (directly) or deno. It doesn't look like there's a lot of information or plugins to just plug-and-play, so would possibly need to do custom esbuild plugin work.

**Comment by shah** [comment]
Thanks for the summary Ben. How about these options?

* [Using Twind with Deno](https://deno.com/manual@v1.32.3/advanced/jsx_dom/twind)
* I've seen UnoCSS esm.sh available -- does that help?

**Comment by bpevs** [comment]
> [Using Twind with Deno](https://deno.com/manual@v1.32.3/advanced/jsx_dom/twind)

The twind example is directed at server-side rendering. Not as relevant here.

> I've seen UnoCSS esm.sh available

Any esm.sh dependency could help in running a node.js build script as "deno"; these kinds of systems probably have hooks to integrate their CLI into existing build systems, which is basically what option 2 is.  

## My Recommendation

Note that, while I'm not against having it in the future, I don't want to put in the work to look into integrating option 2 into bext system currently. There are quite a few unknowns, I am not looking to use this feature myself, and there should be pretty valid workarounds.

If moving forward on this path, I'd recommend working towards option 1 [using a CDN Runtime option](https://unocss.dev/integrations/runtime). You can then work on converting their node.js-driven CLI process from into a deno script/system. If you have a deno-driven system that works (especially if it utilizes esbuild), I'd be happy to explore integrating it into bext via some kind of plugin system, which would likely make the system a bit smoother.
