### ISSUE TITLE
issues getting bext to work

### ISSUE THREAD

**Issue by plutack** [bpevs/bext#7]
hello, 
is there a reason you didn't offer the preact example as a boiler plate on its own since bext is dependent on folder structure? I think it might be better to have that, as i initially thought bext was going to do the whole folder structure boilerplate initialization .

**Comment by bpevs** [comment]
The only reason I didn't was to make all the code more consolidated. But hmmmmm yeah that'd probably make sense. Also, in actuality, those dirs should probably be configurable. Some of this stuff is a bit more out-of-date than it should be anyways, so let me make those changes when I find a bit of time.

**Comment by plutack** [comment]
I was eventually able to find your boilerplate repo template . I think it would be super nice to at least link it alongside or instead of your extension favioli
Or perhaps swap out the examples/preact link to the boilerplate repo in the Readme?

**Comment by bpevs** [comment]
mmmm I don't think that was existing haha.  If you found [deno_web_extension_starter](https://github.com/bpevs/deno_web_extension_starter), this repo actually predates bext, and shouldn't be using it (looking at it right now, I see some references, but that's actually a mistake 😅

But I just now adapted the examples/preact into https://github.com/bpevs/bext_preact_template, so that one should be the canonical example boilerplate.

Sorry about the confusion.

**Comment by plutack** [comment]
That's surprising..I have started writing code using it as a template.i haven't gotten to far perse but I did use bext to build the template and it works

Or do you mean.that even that is "bloated" to serve as a template? Cos I have done some stripping along the way actually.

**Comment by bpevs** [comment]
Oh no, it should work. The code is all compatible with bext because that repo is the predecessor (I consolidated my work from that repo in order to build bext) 😛 It just has some extra stuff that is not necessary (the code you pulled should still work if you remove `build.ts`).

By all means feel free to use it if it works for you! But for anyone in the future reading this, [the new template](https://github.com/bpevs/bext_preact_template) will probably be clearer.
